# Generated by Django 6.0.5 on 2026-05-29 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('solver_type', models.CharField(choices=[('steady_conduction', 'Steady Conduction'), ('convection_diffusion', 'Convection-Diffusion'), ('transient', 'Transient Heat'), ('inverse', 'Inverse Problem')], default='steady_conduction', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('mesh_done', 'Mesh Complete'), ('setup_done', 'Setup Complete'), ('solved', 'Solved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesh_type', models.CharField(max_length=50)),
                ('mesh_str', models.TextField()),
                ('mesh_params', models.JSONField()),
                ('mesh_plot_path', models.CharField(blank=True, max_length=300)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mesh_config', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesh_plot_path', models.CharField(blank=True, max_length=300)),
                ('solution_plot_path', models.CharField(blank=True, max_length=300)),
                ('solution_data', models.JSONField(default=list)),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('solve_time_s', models.FloatField(null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=5)),
                ('bc_config', models.JSONField()),
                ('solver_params', models.JSONField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_config', to='projects.project')),
            ],
        ),
    ]
